server:
  port: 8080

spring:
   config:
     import: application-secret.yml
   datasource:
     driver-class-name: ${db.driver}
     url: ${db.url}
     username: ${db.username}
     password: ${db.password}
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html